apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  LOCATIONAPI_EVENTS_NATS_URL: "{{ .Values.api.events.nats.url }}"
  LOCATIONAPI_EVENTS_NATS_PUBLISHPREFIX: "{{ .Values.api.events.nats.publishPrefix }}"
  LOCATIONAPI_EVENTS_NATS_QUEUEGROUP: "{{ .Values.api.events.nats.queueGroup }}"
  LOCATIONAPI_EVENTS_NATS_SOURCE: "{{ .Values.api.events.nats.source }}"
  LOCATIONAPI_EVENTS_NATS_CONNECTTIMEOUT: "{{ .Values.api.events.nats.connectTimeout }}"
  LOCATIONAPI_EVENTS_NATS_SHUTDOWNTIMEOUT: "{{ .Values.api.events.nats.shutdownTimeout }}"
{{- if .Values.api.events.nats.credsSecretName }}
  LOCATIONAPI_EVENTS_NATS_CREDSFILE: "{{ .Values.api.events.nats.credsFile }}"
{{- end }}
  LOCATIONAPI_OIDC_ENABLED: "{{ .Values.api.oidc.enabled }}"
  LOCATIONAPI_OIDC_AUDIENCE: "{{ .Values.api.oidc.audience }}"
  LOCATIONAPI_OIDC_ISSUER: "{{ .Values.api.oidc.issuer }}"
  LOCATIONAPI_OIDC_JWKS_REMOTE_TIMEOUT: "{{ .Values.api.oidc.jwksRemoteTimeout }}"
  LOCATIONAPI_SERVER_LISTEN: ":{{ .Values.api.listenPort }}"
  LOCATIONAPI_SERVER_SHUTDOWN_GRACE_PERIOD: "{{ .Values.api.shutdownGracePeriod }}"
{{- with .Values.api.trustedProxies }}
  LOCATIONAPI_SERVER_TRUSTED_PROXIES: "{{ join " " . }}"
{{- end }}
